version: 0.0
os: linux
files:
  - source: /homework/
    destination: /var/www/homework/homework/
hooks:
  ApplicationStart:
    - location: scripts/restart_apache.sh
      timeout: 300
      runas: root